# .github/workflows/generate-lockfile.yml
name: Generate lockfile (one-time)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # (sem cache aqui, porque o lockfile ainda não existe)

      # Gera SOMENTE o package-lock.json (não instala node_modules)
      - name: Create package-lock.json only
        run: |
          npm config set package-lock true
          npm i --package-lock-only --no-audit --fund=false
          test -f package-lock.json || (echo "package-lock.json NOT created" && exit 1)

      # Commita o lockfile na main
      - name: Commit lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add package-lock.json"
          file_pattern: "package-lock.json"
          branch: main
